// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBsgljf6ABQGfQmGt1GH2PWSWUa2Qm9bN8',
    appId: '1:759762188544:web:d2b2e9d51b0dcd39aa9be5',
    messagingSenderId: '759762188544',
    projectId: 'zapcall-37e19',
    authDomain: 'zapcall-37e19.firebaseapp.com',
    storageBucket: 'zapcall-37e19.firebasestorage.app',
    measurementId: 'G-PXMXQW5DX7',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyClMX9r8CpiWz5K_90L2TTvdDaF303TacY',
    appId: '1:759762188544:android:d90cf72a138d2e2caa9be5',
    messagingSenderId: '759762188544',
    projectId: 'zapcall-37e19',
    storageBucket: 'zapcall-37e19.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAB85INNQRnRIcoddzDBsCyJK4oAna4oIo',
    appId: '1:759762188544:ios:0cab89ba87dc93b0aa9be5',
    messagingSenderId: '759762188544',
    projectId: 'zapcall-37e19',
    storageBucket: 'zapcall-37e19.firebasestorage.app',
    iosBundleId: 'dev.albinpk.zapcall',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAB85INNQRnRIcoddzDBsCyJK4oAna4oIo',
    appId: '1:759762188544:ios:0cab89ba87dc93b0aa9be5',
    messagingSenderId: '759762188544',
    projectId: 'zapcall-37e19',
    storageBucket: 'zapcall-37e19.firebasestorage.app',
    iosBundleId: 'dev.albinpk.zapcall',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBsgljf6ABQGfQmGt1GH2PWSWUa2Qm9bN8',
    appId: '1:759762188544:web:0ef4e6e856d312e1aa9be5',
    messagingSenderId: '759762188544',
    projectId: 'zapcall-37e19',
    authDomain: 'zapcall-37e19.firebaseapp.com',
    storageBucket: 'zapcall-37e19.firebasestorage.app',
    measurementId: 'G-YS81EQT7QP',
  );
}
